### PR TITLE
Some refactorings...

### PR DESCRIPTION
**Pull request by Alonely0**
Hey, this is the guy from Reddit, here's my PR :)
I haven't tested it with the driver, so you'll have to tell me if I've messed up somewhere (especially with the conflict mess that you made by partially porting stuff that I was implementing, but according to git I managed to resolve it cleanly). Skim through the commit notes to see what I've done, and btw, this is ready for publishing on crates.io.

### CODE REVIEW

**Comment by Alonely0** [comment]
Hey, you know you can just click "merge" and have all my patches applied, instead of partially implementing stuff, right? This only makes git angrier and angrier...

**Comment by devhsoj** [comment]
Hahaha yes I did, I just had a ton of changes before your PR was up. I'll merge this when I get some free time.

**Comment by devhsoj** [comment]
I liked all your changes and they all make sense, thanks for the help! I did however decide to keep Cargo.lock out of the .gitignore since this is a binary build rather than a library.

See: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by devhsoj** [comment]
Ah I see why you did it now, keeping it in. 😅

**Comment by Alonely0** [comment]
I'm glad the changes were good. BTW don't ever upload your .vscode to GitHub **ever again**. These can get OS-dependant and/or vscode-version-dependant, and I just learnt that the hard way. When I started working on Paggo, rust-analyzer immediately broke, and I had to debug it for half an hour because it was looking for a ".\Cargo.toml", which it couldn't find because I'm on Linux, and it uses normal slashes for directories. After that half an hour of debugging and tweaking rust-analyzer's config, I realized it was your .vscode created on Windows messing with my rust-analyzer on Linux.

**Comment by devhsoj** [comment]
Yeah I know, that was not intended, my .gitignore got reset in my changes and the .vscode/ entry was removed locally so when I pushed it was included.

**Pull request merged**
